# Generated by Django 3.2 on 2022-06-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_notificaçõesmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaçõesmodel',
            name='status',
            field=models.CharField(default='Esperando status', max_length=200, null=True, verbose_name='Status'),
        ),
    ]
