# Generated by Django 3.2 on 2022-06-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_notificacoes_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacoes',
            name='cod',
        ),
        migrations.RemoveField(
            model_name='notificacoes',
            name='cod_tipo',
        ),
        migrations.AddField(
            model_name='notificacoes',
            name='notificationCode',
            field=models.CharField(max_length=200, null=True, verbose_name='Código Notificação'),
        ),
        migrations.AddField(
            model_name='notificacoes',
            name='notificationType',
            field=models.CharField(max_length=200, null=True, verbose_name='Tipo do código'),
        ),
    ]
